version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    expose:
      - "5000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
